import sys

from app.core.database import Base, SessionLocal, engine
from app.models.job_posting import JobPosting


SEED_JOBS = [
    {
        "title": "Backend Engineer",
        "company_name": "Tokyo FinTech Labs",
        "company_type": "自社开发",
        "location": "东京",
        "industry": "金融",
        "required_skills": ["Python", "FastAPI", "SQL"],
        "preferred_skills": ["AWS", "Docker", "Linux"],
        "japanese_level": "N2",
        "experience_requirement": "1年以上",
        "initial_salary": 300000,
        "job_url": "https://example.com/jobs/1",
    },
    {
        "title": "Java Web Engineer",
        "company_name": "Osaka System Works",
        "company_type": "受托开发",
        "location": "大阪",
        "industry": "制造",
        "required_skills": ["Java", "Spring Boot", "SQL"],
        "preferred_skills": ["Linux", "Docker", "AWS"],
        "japanese_level": "N2",
        "experience_requirement": "1年以上",
        "initial_salary": 280000,
        "job_url": "https://example.com/jobs/2",
    },
    {
        "title": "Frontend Engineer",
        "company_name": "Shibuya Web Studio",
        "company_type": "自社开发",
        "location": "东京",
        "industry": "互联网",
        "required_skills": ["JavaScript", "React", "TypeScript"],
        "preferred_skills": None,
        "japanese_level": None,
        "experience_requirement": "新卒",
        "initial_salary": 260000,
        "job_url": "https://example.com/jobs/3",
    },
    {
        "title": "Infrastructure Engineer",
        "company_name": "Cloud Bridge Japan",
        "company_type": "SES",
        "location": "东京",
        "industry": "互联网",
        "required_skills": ["Linux", "Network", "Shell"],
        "preferred_skills": ["AWS", "Terraform", "Docker"],
        "japanese_level": "N2",
        "experience_requirement": "1年以上",
        "initial_salary": 290000,
        "job_url": "https://example.com/jobs/4",
    },
    {
        "title": "Database Engineer",
        "company_name": "Kansai Data Solutions",
        "company_type": "受托开发",
        "location": "大阪",
        "industry": "金融",
        "required_skills": ["SQL", "PostgreSQL", "Linux"],
        "preferred_skills": ["Python", "ETL", "AWS"],
        "japanese_level": "N2",
        "experience_requirement": "3年以上",
        "initial_salary": 340000,
        "job_url": "https://example.com/jobs/5",
    },
    {
        "title": "AI Application Engineer",
        "company_name": "Akasaka AI Partners",
        "company_type": "自社开发",
        "location": "东京",
        "industry": "互联网",
        "required_skills": ["Python", "API", "SQL"],
        "preferred_skills": ["LLM", "LangChain", "FastAPI"],
        "japanese_level": "N2",
        "experience_requirement": "1年以上",
        "initial_salary": 320000,
        "job_url": "https://example.com/jobs/6",
    },
    {
        "title": "C++ Software Engineer",
        "company_name": "Nagoya Embedded Tech",
        "company_type": "自社开发",
        "location": "名古屋",
        "industry": "制造",
        "required_skills": ["C++", "Linux", "Git"],
        "preferred_skills": ["Network", "Python", "CI/CD"],
        "japanese_level": "N2",
        "experience_requirement": "1年以上",
        "initial_salary": 300000,
        "job_url": "https://example.com/jobs/7",
    },
    {
        "title": "QA Automation Engineer",
        "company_name": "Yokohama Quality Base",
        "company_type": "派遣",
        "location": "横滨",
        "industry": "医疗",
        "required_skills": ["Testing", "Python", "SQL"],
        "preferred_skills": None,
        "japanese_level": "N3",
        "experience_requirement": "新卒",
        "initial_salary": 250000,
        "job_url": "https://example.com/jobs/8",
    },
    {
        "title": "Full Stack Engineer",
        "company_name": "Fukuoka Product Hub",
        "company_type": "自社开发",
        "location": "福冈",
        "industry": "互联网",
        "required_skills": ["React", "Python", "SQL"],
        "preferred_skills": ["FastAPI", "AWS", "TypeScript"],
        "japanese_level": "N3",
        "experience_requirement": "1年以上",
        "initial_salary": 280000,
        "job_url": "https://example.com/jobs/9",
    },
    {
        "title": "Security Engineer",
        "company_name": "Tokyo Secure Systems",
        "company_type": "SES",
        "location": "东京",
        "industry": "金融",
        "required_skills": ["Linux", "Network", "Security"],
        "preferred_skills": ["AWS", "Python", "SIEM"],
        "japanese_level": "N1",
        "experience_requirement": "3年以上",
        "initial_salary": 380000,
        "job_url": "https://example.com/jobs/10",
    },
    {
        "title": "Cloud Support Engineer",
        "company_name": "Sapporo Cloud Desk",
        "company_type": "受托开发",
        "location": "札幌",
        "industry": "互联网",
        "required_skills": ["Linux", "AWS", "Network"],
        "preferred_skills": ["Python", "Docker", "Monitoring"],
        "japanese_level": None,
        "experience_requirement": "1年以上",
        "initial_salary": 270000,
        "job_url": "https://example.com/jobs/11",
    },
    {
        "title": "Medical Systems Engineer",
        "company_name": "Kyoto Health IT",
        "company_type": "受托开发",
        "location": "京都",
        "industry": "医疗",
        "required_skills": ["Java", "SQL", "Linux"],
        "preferred_skills": ["Spring Boot", "Oracle", "Testing"],
        "japanese_level": "N2",
        "experience_requirement": "1年以上",
        "initial_salary": 285000,
        "job_url": "https://example.com/jobs/12",
    },
    {
        "title": "Data Analyst Engineer",
        "company_name": "Tokyo Data Market",
        "company_type": "自社开发",
        "location": "东京",
        "industry": "互联网",
        "required_skills": ["SQL", "Python", "Excel"],
        "preferred_skills": ["Pandas", "BI", "Statistics"],
        "japanese_level": "N2",
        "experience_requirement": "新卒",
        "initial_salary": 270000,
        "job_url": "https://example.com/jobs/13",
    },
    {
        "title": "DevOps Engineer",
        "company_name": "Roppongi Platform Co",
        "company_type": "自社开发",
        "location": "东京",
        "industry": "互联网",
        "required_skills": ["Linux", "Docker", "AWS"],
        "preferred_skills": ["Terraform", "Kubernetes", "Python"],
        "japanese_level": "N2",
        "experience_requirement": "3年以上",
        "initial_salary": 400000,
        "job_url": "https://example.com/jobs/14",
    },
    {
        "title": "SES Java Engineer",
        "company_name": "Nihon IT Service",
        "company_type": "SES",
        "location": "东京",
        "industry": "金融",
        "required_skills": ["Java", "SQL", "Git"],
        "preferred_skills": ["Spring Boot", "Linux", "AWS"],
        "japanese_level": "N3",
        "experience_requirement": "新卒",
        "initial_salary": 240000,
        "job_url": "https://example.com/jobs/15",
    },
    {
        "title": "Manufacturing IoT Engineer",
        "company_name": "Nagoya Smart Factory",
        "company_type": "自社开发",
        "location": "名古屋",
        "industry": "制造",
        "required_skills": ["C++", "Python", "Network"],
        "preferred_skills": ["IoT", "Linux", "MQTT"],
        "japanese_level": "N2",
        "experience_requirement": "1年以上",
        "initial_salary": 310000,
        "job_url": "https://example.com/jobs/16",
    },
    {
        "title": "React Native Engineer",
        "company_name": "Shinjuku Mobile Lab",
        "company_type": "自社开发",
        "location": "东京",
        "industry": "互联网",
        "required_skills": ["React", "TypeScript", "API"],
        "preferred_skills": ["React Native", "Testing", "Firebase"],
        "japanese_level": "N3",
        "experience_requirement": "1年以上",
        "initial_salary": 300000,
        "job_url": "https://example.com/jobs/17",
    },
    {
        "title": "Banking System Engineer",
        "company_name": "Marunouchi Core Banking",
        "company_type": "受托开发",
        "location": "东京",
        "industry": "金融",
        "required_skills": ["Java", "SQL", "Linux"],
        "preferred_skills": ["COBOL", "Oracle", "Shell"],
        "japanese_level": "N1",
        "experience_requirement": "3年以上",
        "initial_salary": 360000,
        "job_url": "https://example.com/jobs/18",
    },
    {
        "title": "Python API Engineer",
        "company_name": "Minato SaaS Factory",
        "company_type": "自社开发",
        "location": "东京",
        "industry": "互联网",
        "required_skills": ["Python", "FastAPI", "Git"],
        "preferred_skills": ["PostgreSQL", "Docker", "AWS"],
        "japanese_level": "N3",
        "experience_requirement": "新卒",
        "initial_salary": 270000,
        "job_url": "https://example.com/jobs/19",
    },
    {
        "title": "Network Engineer",
        "company_name": "Kobe Network Service",
        "company_type": "派遣",
        "location": "神户",
        "industry": "制造",
        "required_skills": ["Network", "Linux", "Troubleshooting"],
        "preferred_skills": ["Cisco", "Security", "Shell"],
        "japanese_level": "N2",
        "experience_requirement": "1年以上",
        "initial_salary": 260000,
        "job_url": "https://example.com/jobs/20",
    },
    {
        "title": "Healthcare Backend Engineer",
        "company_name": "Osaka Medical Cloud",
        "company_type": "自社开发",
        "location": "大阪",
        "industry": "医疗",
        "required_skills": ["Python", "SQL", "API"],
        "preferred_skills": ["FastAPI", "AWS", "Security"],
        "japanese_level": "N2",
        "experience_requirement": "1年以上",
        "initial_salary": 305000,
        "job_url": "https://example.com/jobs/21",
    },
    {
        "title": "Junior Web Engineer",
        "company_name": "Hakata Web Works",
        "company_type": "受托开发",
        "location": "福冈",
        "industry": "互联网",
        "required_skills": ["HTML", "CSS", "JavaScript"],
        "preferred_skills": ["React", "TypeScript", "Git"],
        "japanese_level": "N3",
        "experience_requirement": "新卒",
        "initial_salary": 230000,
        "job_url": "https://example.com/jobs/22",
    },
    {
        "title": "Machine Learning Engineer",
        "company_name": "Tokyo Vision AI",
        "company_type": "自社开发",
        "location": "东京",
        "industry": "互联网",
        "required_skills": ["Python", "Machine Learning", "SQL"],
        "preferred_skills": ["PyTorch", "Docker", "AWS"],
        "japanese_level": "N2",
        "experience_requirement": "3年以上",
        "initial_salary": 420000,
        "job_url": "https://example.com/jobs/23",
    },
    {
        "title": "ERP System Engineer",
        "company_name": "Tokyo Enterprise Apps",
        "company_type": "受托开发",
        "location": "东京",
        "industry": "制造",
        "required_skills": ["Java", "SQL", "Business Analysis"],
        "preferred_skills": None,
        "japanese_level": "N1",
        "experience_requirement": "3年以上",
        "initial_salary": 370000,
        "job_url": "https://example.com/jobs/24",
    },
    {
        "title": "Cloud Backend Engineer",
        "company_name": "Yokohama SaaS Dock",
        "company_type": "自社开发",
        "location": "横滨",
        "industry": "互联网",
        "required_skills": ["Python", "PostgreSQL", "Linux"],
        "preferred_skills": ["FastAPI", "Docker", "AWS"],
        "japanese_level": "N2",
        "experience_requirement": "1年以上",
        "initial_salary": 315000,
        "job_url": "https://example.com/jobs/25",
    },
]


def seed_jobs(reset: bool = False) -> None:
    if reset:
        Base.metadata.drop_all(bind=engine)

    Base.metadata.create_all(bind=engine)

    db = SessionLocal()
    try:
        existing_count = db.query(JobPosting).count()
        if existing_count:
            print(f"job_postings already has {existing_count} rows, skip seeding.")
            return

        db.add_all(JobPosting(**job) for job in SEED_JOBS)
        db.commit()
        print(f"Seeded {len(SEED_JOBS)} job postings.")
    finally:
        db.close()


if __name__ == "__main__":
    seed_jobs(reset="--reset" in sys.argv)
